### ISSUE TITLE
Request For Next `Astro City Mini` Release Timeline Clarifications

### ISSUE THREAD

**Issue by loganknecht** [acm-cfw/acm-cfw.github.io#47]
Hello!

Thank you so much for making this awesome custom firmware.

I apologize in advance for making this issue, but I am super eager to hear when the next release is going to get dropped.

Is there any information regarding when the next release for the Astro City Mini will arrive?

**Comment by acmeplus** [comment]
There are many projects in line and my time is limited. Right now I'm focused on finish a new firmware for the RG35XX, and after that I plan to create batocera updates for the ACM and E2M, but those will be mostly getting packages updated to the latest batocera baseline (e.g. PPSSPP being updated to 1.15). Due to the limited time I don't have plans to work in major changes for those platforms unless there's something significantly broken.

**Comment by loganknecht** [comment]
Understood. I don't want to pressure you to do anything. I really appreciate you making this available in the first place. I'm a big fan of your YouTube channel :)

Closing as answered.
